[package]
name = "dec01"
version = "0.1.0"
authors = ["Mikael Lundin <mikael.lundin@f24s.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
